---
# cPanel Git Deployment Configuration
# This file must be in the top-level directory of the repository
# Repository Path: /home/tammerify/public_html/
# All files will be deployed directly to public_html

deployment:
  tasks:
    # Set deployment path to public_html directly
    - export DEPLOYPATH=/home/tammerify/public_html/
    
    # Copy root index.php FIRST (most important file - must be preserved)
    - /bin/cp -f index.php $DEPLOYPATH/index.php || /bin/cp index.php $DEPLOYPATH
    
    # Copy entire core directory to deployment path
    - /bin/cp -R core $DEPLOYPATH
    
    # Copy assets directory if exists
    - /bin/cp -R assets $DEPLOYPATH || true
    
    # Copy robots.txt if exists
    - /bin/cp robots.txt $DEPLOYPATH || true
    
    # Copy web.config if exists
    - /bin/cp web.config $DEPLOYPATH || true
    
    # Create required storage directories if they don't exist
    - /bin/mkdir -p $DEPLOYPATH/core/storage/logs
    - /bin/mkdir -p $DEPLOYPATH/core/storage/framework/cache
    - /bin/mkdir -p $DEPLOYPATH/core/storage/framework/cache/data
    - /bin/mkdir -p $DEPLOYPATH/core/storage/framework/sessions
    - /bin/mkdir -p $DEPLOYPATH/core/storage/framework/views
    - /bin/mkdir -p $DEPLOYPATH/core/storage/app/public
    - /bin/mkdir -p $DEPLOYPATH/core/bootstrap/cache
    
    # Create .gitkeep files to ensure directories are tracked
    - /bin/touch $DEPLOYPATH/core/storage/logs/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/storage/framework/cache/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/storage/framework/cache/data/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/storage/framework/sessions/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/storage/framework/views/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/storage/app/public/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/bootstrap/cache/.gitkeep || true
    
    # Set proper permissions for storage and cache directories (777 for maximum compatibility)
    - /bin/chmod -R 777 $DEPLOYPATH/core/storage
    - /bin/chmod -R 777 $DEPLOYPATH/core/bootstrap/cache
    
    # Set ownership (adjust username if needed)
    - /bin/chown -R tammerify:tammerify $DEPLOYPATH/core/storage || true
    - /bin/chown -R tammerify:tammerify $DEPLOYPATH/core/bootstrap/cache || true
    
    # Clear Laravel cache files that contain local paths
    - /bin/rm -f $DEPLOYPATH/core/bootstrap/cache/config.php || true
    - /bin/rm -f $DEPLOYPATH/core/bootstrap/cache/services.php || true
    - /bin/rm -f $DEPLOYPATH/core/bootstrap/cache/routes.php || true
    - /bin/rm -f $DEPLOYPATH/core/bootstrap/cache/packages.php || true
    
    # Recreate .gitkeep in bootstrap/cache after clearing cache
    - /bin/touch $DEPLOYPATH/core/bootstrap/cache/.gitkeep || true
    
    # Clear framework cache files
    - /bin/rm -rf $DEPLOYPATH/core/storage/framework/cache/data/* || true
    - /bin/rm -rf $DEPLOYPATH/core/storage/framework/views/* || true
    - /bin/rm -rf $DEPLOYPATH/core/storage/framework/sessions/* || true
    
    # Recreate .gitkeep files after clearing
    - /bin/touch $DEPLOYPATH/core/storage/framework/cache/data/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/storage/framework/views/.gitkeep || true
    - /bin/touch $DEPLOYPATH/core/storage/framework/sessions/.gitkeep || true
    
    # Protect sensitive files with .htaccess
    - /bin/echo "# Protect .env file" > $DEPLOYPATH/core/.htaccess
    - /bin/echo "<Files .env>" >> $DEPLOYPATH/core/.htaccess
    - /bin/echo "Order allow,deny" >> $DEPLOYPATH/core/.htaccess
    - /bin/echo "Deny from all" >> $DEPLOYPATH/core/.htaccess
    - /bin/echo "</Files>" >> $DEPLOYPATH/core/.htaccess

