---
# cPanel Git Deployment Configuration
# This file must be in the top-level directory of the repository
# Repository Path: /home/tammerify/public_html/asaas
# All files will be deployed directly to this directory

deployment:
  tasks:
    # Set deployment path to match cPanel repository path
    - export DEPLOYPATH=/home/tammerify/public_html/asaas/
    
    # Copy entire core directory to deployment path
    - /bin/cp -R core $DEPLOYPATH
    
    # Copy root index.php to deployment path
    - /bin/cp index.php $DEPLOYPATH
    
    # Copy assets directory if exists
    - /bin/cp -R assets $DEPLOYPATH || true
    
    # Copy robots.txt if exists
    - /bin/cp robots.txt $DEPLOYPATH || true
    
    # Copy web.config if exists
    - /bin/cp web.config $DEPLOYPATH || true
    
    # Set proper permissions for storage and cache directories
    - /bin/chmod -R 775 $DEPLOYPATH/core/storage
    - /bin/chmod -R 775 $DEPLOYPATH/core/bootstrap/cache
    
    # Protect sensitive files with .htaccess
    - /bin/echo "# Protect .env file" > $DEPLOYPATH/core/.htaccess
    - /bin/echo "<Files .env>" >> $DEPLOYPATH/core/.htaccess
    - /bin/echo "Order allow,deny" >> $DEPLOYPATH/core/.htaccess
    - /bin/echo "Deny from all" >> $DEPLOYPATH/core/.htaccess
    - /bin/echo "</Files>" >> $DEPLOYPATH/core/.htaccess

