<?php

namespace App\Helpers\Payment;

class GlobalCurrency
{
    /**
     * Get list of all supported currencies with their symbols
     * 
     * @return array
     */
    public static function script_currency_list(): array
    {
        return [
            'USD' => '$',
            'EUR' => '€',
            'GBP' => '£',
            'JPY' => '¥',
            'AUD' => 'A$',
            'CAD' => 'C$',
            'CHF' => 'CHF',
            'CNY' => '¥',
            'INR' => '₹',
            'KWD' => 'د.ك',
            'AED' => 'د.إ',
            'SAR' => 'ر.س',
            'QAR' => 'ر.ق',
            'OMR' => 'ر.ع',
            'BHD' => '.د.ب',
            'JOD' => 'د.ا',
            'EGP' => 'ج.م',
            'ILS' => '₪',
            'TRY' => '₺',
            'RUB' => '₽',
            'ZAR' => 'R',
            'BRL' => 'R$',
            'MXN' => '$',
            'SGD' => 'S$',
            'HKD' => 'HK$',
            'NZD' => 'NZ$',
            'NOK' => 'kr',
            'SEK' => 'kr',
            'DKK' => 'kr',
            'PLN' => 'zł',
            'CZK' => 'Kč',
            'HUF' => 'Ft',
            'RON' => 'lei',
            'BGN' => 'лв',
            'HRK' => 'kn',
            'PHP' => '₱',
            'IDR' => 'Rp',
            'THB' => '฿',
            'MYR' => 'RM',
            'VND' => '₫',
            'KRW' => '₩',
            'TWD' => 'NT$',
            'PKR' => '₨',
            'BDT' => '৳',
            'LKR' => 'Rs',
            'NPR' => 'Rs',
            'AFN' => '؋',
            'AMD' => '֏',
            'AZN' => '₼',
            'BYN' => 'Br',
            'GEL' => '₾',
            'KZT' => '₸',
            'KGS' => 'с',
            'MDL' => 'L',
            'TJS' => 'ЅМ',
            'TMT' => 'm',
            'UAH' => '₴',
            'UZS' => 'лв',
            'NGN' => '₦',
            'GHS' => '₵',
            'KES' => 'KSh',
            'UGX' => 'USh',
            'TZS' => 'TSh',
            'ETB' => 'Br',
            'MAD' => 'د.م.',
            'TND' => 'د.ت',
            'DZD' => 'د.ج',
            'XOF' => 'CFA',
            'XAF' => 'FCFA',
            'ZMW' => 'ZK',
            'BWP' => 'P',
            'MWK' => 'MK',
            'MZN' => 'MT',
            'MGA' => 'Ar',
            'MUR' => '₨',
            'SCR' => '₨',
            'ARS' => '$',
            'CLP' => '$',
            'COP' => '$',
            'PEN' => 'S/',
            'UYU' => '$U',
            'PYG' => '₲',
            'BOB' => 'Bs.',
            'VES' => 'Bs.S',
            'CRC' => '₡',
            'GTQ' => 'Q',
            'HNL' => 'L',
            'NIO' => 'C$',
            'PAB' => 'B/.',
            'DOP' => 'RD$',
            'JMD' => 'J$',
            'BBD' => '$',
            'BZD' => '$',
            'BSD' => '$',
            'BMD' => '$',
            'KYD' => '$',
            'TTD' => 'TT$',
            'XCD' => '$',
            'AWG' => 'ƒ',
            'ANG' => 'ƒ',
            'GYD' => '$',
            'SRD' => '$',
            'FJD' => '$',
            'PGK' => 'K',
            'SBD' => '$',
            'VUV' => 'Vt',
            'NCF' => 'Fr',
            'XPF' => 'Fr',
            'NOK' => 'kr',
            'ISK' => 'kr',
            'ALL' => 'L',
            'BAM' => 'КМ',
            'RSD' => 'din',
            'MKD' => 'ден',
            'XDR' => 'SDR',
            'XAU' => 'Au',
            'XAG' => 'Ag',
            'BTC' => '₿',
            'ETH' => 'Ξ',
            'LTC' => 'Ł',
        ];
    }
}




