version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php"
  user: ""
  group: ""
  env:
    APP_RUNTIME: RoadRunner

http:
  address: 0.0.0.0:8000
  middleware: ["gzip"]
  pool:
    num_workers: 4
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  headers:
    response:
      X-Powered-By: "RoadRunner"

static:
  dir:   "public"
  forbid: [".htaccess", ".php"]

reload:
  interval: 1s
  patterns: [".php"]
  services:
    http:
      recursive: true
      ignore: ["vendor"]
      dirs: ["app", "config", "database", "routes"]

logs:
  mode: development
  level: debug
  output: stdout
  err_output: stderr
  encoding: console
  time_format: "15:04:05"

metrics:
  address: localhost:2112

debug:
  address: localhost:6060
  pprof: false

